# Return early on non-interactive sessions, lest scp not work.
[[ $- == *i* ]] || return

# OS dependent config
OS=$(uname)
if [ "$OS" = Linux ]; then
  alias ls='ls --color=auto'

  shopt -s direxpand
elif [ "$OS" = Darwin ]; then
  alias ls='ls -G' # color

  #[ -f /usr/local/bin/brew ] && PATH="/usr/local/bin:/usr/local/sbin:$PATH"
  # we can't use zsh yet, macOS
  export BASH_SILENCE_DEPRECATION_WARNING=1
fi

alias ..='cd ..'

alias dudot='du -hd 1'

alias ll='ls -Alh --color=auto'

alias g=git
# -x means include processes without an attached tty
alias psx='ps x | less'

# install paccache via `pacman -S pacman-contrib`
alias pacupdateclean='\
  sudo pacman -Syu && \
  paccache --remove --uninstalled --keep 3 && \
  paccache --remove --keep 3'

function gcheckoutremote {
  # Validate argument
  [ -z "$1" ] && 2>&1 echo 'Usage: gcheckoutremote $REMOTE_NAME' && return
  git fetch "$1"
  # git ls-remote... list all branches on a remote
  # sed ... capture just the branch name
  # fzf ... allow user to select a branch
  # xargs ... checkout selected branch
  git ls-remote --heads "$1" | \
    sed 's/.*refs\/heads\/\([a-zA-Z0-9./_-]*\)/\1/' | \
    fzf --no-multi | \
    xargs git checkout
}

alias grepi='grep -i'

# Text editors
alias emacs='emacs -nw' # default to console-based emacs

PS1='\w\$ '

if type nvim >/dev/null 2>&1; then
  export VISUAL=nvim
elif type vim >/dev/null 2>&1; then
  export VISUAL=vim
elif type vi >/dev/null 2>&1; then
  export VISUAL=vi
else
  echo "You don't have a vi-compliant editor!" >&2
fi

export EDITOR=$VISUAL

# golang dev
[ -d "$HOME/go" ] && export GOPATH="$HOME/go"



if [[ -z "$TERMINAL" ]]; then
  # TODO check if alacritty is available
  export TERMINAL='alacritty'
fi

if [[ -f "$HOME/.setup-path.bash" ]]; then
  source "$HOME/.setup-path.bash"
else
  echo "oops, didn't find $HOME/.setup-path.bash" >&2
fi

# source config files, if they exist
files=(
  "$HOME/.fzf.bash"
  /usr/local/etc/bash_completion
  "$HOME/.rvm/scripts/rvm"
  "$HOME/.flutter-completion"
  "$HOME/.cargo/env"
  "$HOME/.local/share/gem/ruby/3.3.0/bin"
)

for i in "${files[@]}"; do
  # shellcheck source=/dev/null
  [ -f "$i" ] && source "$i"
done

# fzf
if type fzf >/dev/null 2>&1; then
  alias checkout="git branch --list --sort=-committerdate | sed 's/^\*/ /' | fzf | xargs git checkout"
  alias branchd="git branch --list --sort=-committerdate | sed -E 's/^[ *]+//' | fzf --multi | xargs git branch -d --force"
else
  echo "Warning! fzf not installed, and it's awesome!" 1>&2
fi

# opam configuration
test -r "$HOME/.opam/opam-init/init.sh" && . "$HOME/.opam/opam-init/init.sh" > /dev/null 2> /dev/null || true

# source local-machine specific config if it exists
# shellcheck source=/dev/null
if [[ -f "$HOME/.bashrc.local" && -z "$BASH_RC_LOCAL_SET" ]]; then
  source "$HOME/.bashrc.local"
  export BASH_RC_LOCAL_SET=1
fi

# You must have run `sudo systemctl --user enable ssh-agent.service`
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

function count_duplicate_path_entries {
  COUNT=$(echo "$PATH" | tr : '\n' | sort | uniq -d | wc -l)
  if [ "$COUNT" -gt 0 ]; then
    echo 'Warning! You have duplicate entries in your PATH:'
    echo "$PATH" | tr : '\n' | sort | uniq -d
  fi
}

function detect_autogenerated_lines {
  CURRENT_SCRIPT_NAME="${BASH_SOURCE[0]}"
  LAST_LINE=$(tail -n 1 "$CURRENT_SCRIPT_NAME")
  if [ "$LAST_LINE" != '# Anything after here was auto-generated' ]; then
    echo "Warning! The following has been appended to the end of ${CURRENT_SCRIPT_NAME}:"
    echo
    tput setaf 1
    perl -e 'print reverse <>' <"$CURRENT_SCRIPT_NAME" | sed -n '1,/Anything after here was auto-generated/p' | perl -e 'print reverse <>'

    tput sgr0
  fi
}

# https://www.architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/#.Uydjga1dXDg
if [[ $(uname) == 'Darwin' && -f /etc/paths ]]; then
  PATHS_LENGTH=$(wc -l /etc/paths | awk '{print $1}')
  if [[ "$PATHS_LENGTH" -gt 0 ]]; then
    echo "Warning, you have a populated /etc/paths file that will prepend to your \$PATH var" >&2
  fi
fi

export PATH

count_duplicate_path_entries
detect_autogenerated_lines

alias cdfuzz='cd `rg --files . --glob ".git" | while read LINE; do dirname "$LINE"; done | fzf`'

# Anything after here was auto-generated
