# CIRRUS CONFIGURATION FILE
# https://cirrus-ci.org/guide/writing-tasks/

linux_task:
  container:
    image: debian:bullseye-20200327-slim
  setup_script:
    - apt-get update && apt-get upgrade --yes
    - apt-get install --yes vim git
  matrix:
    - name: "Execute .bashrc"
      script:
        - bash ./.bashrc

mac_task:
  osx_instance:
    image: catalina-base # see https://cirrus-ci.org/guide/macOS/
  matrix:
    - name: "Execute .bashrc"
      script:
        - bash ./.bashrc
