# CIRRUS CONFIGURATION FILE
# https://cirrus-ci.org/guide/writing-tasks/

task: # pinned debian version
  container:
    matrix:
      - image: debian:bullseye-20200327-slim
        # TODO: make this `:latest` when bullseye becomes stable
      - image: debian:bullseye
  setup_script:
    - apt-get update && apt-get upgrade --yes
    - apt-get install --yes vim shellcheck
    - uname -a
    - cat /etc/issue
  matrix:
    - name: "Integrate"
      script:
        - bash ./.bashrc
        - shellcheck --version
        - shellcheck ./scripts/*.sh

task:
  name: macOS
  osx_instance:
    image: catalina-base # see https://cirrus-ci.org/guide/macOS/
  setup_script:
    - brew install shellcheck
    - uname -a
  matrix:
    - name: "Integrate"
      script:
        - bash ./.bashrc
        - shellcheck --version
        - shellcheck ./scripts/*.sh
