# CIRRUS CONFIGURATION FILE
# https://cirrus-ci.org/guide/writing-tasks/

task: # pinned debian version
  name: Linux pinned version
  container:
    image: debian:bullseye-20200327-slim
  setup_script:
    - apt-get update && apt-get upgrade --yes
    - apt-get install --yes vim git
  matrix:
    - name: "Execute .bashrc"
      script:
        - bash ./.bashrc

task: # latest debian version
  name: Linux latest version
  container:
    image: debian:latest
  setup_script:
    - apt-get update && apt-get upgrade --yes
    - apt-get install --yes vim git
  matrix:
    - name: "Execute .bashrc"
      script:
        - bash ./.bashrc

task:
  name: macOS
  osx_instance:
    image: catalina-base # see https://cirrus-ci.org/guide/macOS/
  matrix:
    - name: "Execute .bashrc"
      script:
        - bash ./.bashrc
