" Generated by vim-plug
" Fri Apr  3 17:08:00 2020
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-pairs'].commit = '39f06b8'
silent! let g:plugs['base16-vim'].commit = '6191622'
silent! let g:plugs['coc.nvim'].commit = 'cae97785'
silent! let g:plugs['dart-vim-plugin'].commit = '4375ab9'
silent! let g:plugs['fzf'].commit = '334a4fa'
silent! let g:plugs['fzf.vim'].commit = 'd4d36b4'
silent! let g:plugs['indentLine'].commit = '15aceda'
silent! let g:plugs['vim-airline'].commit = '87d4648'
silent! let g:plugs['vim-airline-themes'].commit = '3fb676b'
silent! let g:plugs['vim-autoread'].commit = '7e83d47'
silent! let g:plugs['vim-eunuch'].commit = '33e875b'
silent! let g:plugs['vim-fugitive'].commit = '0e35c9b'
silent! let g:plugs['vim-gitgutter'].commit = 'b7db78b'
silent! let g:plugs['vim-js'].commit = '3ab7c66'
silent! let g:plugs['vim-jsx-pretty'].commit = '05f9953'
silent! let g:plugs['vim-rhubarb'].commit = '5130596'
silent! let g:plugs['vim-smart-swap'].commit = '7b85673'
silent! let g:plugs['vim-surround'].commit = 'f51a26d'
silent! let g:plugs['yats.vim'].commit = '74cebce'

PlugUpdate!

