# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  bash_rc:
    description: "You know what I mean"
    steps:
      - run:
          name: "execute .bashrc"
          command: bash ./.bashrc
  install_deps:
    description: "Install dependencies"
    steps:
      - run:
          name: "Update repos"
          command: apt-get update && apt-get upgrade --yes
      - run:
          name: "Install deps"
          command: apt-get install --yes vim git
jobs:
  build: # with pinned container
    docker:
      - image: "debian:bullseye-20200327-slim"
    steps:
      - install_deps
      - checkout # CirlcCI command, check out source repo
      - bash_rc
  debian_latest:
    docker:
      - image: "debian:latest"
    steps:
      - install_deps
      - checkout # CirlcCI command, check out source repo
      - bash_rc

workflows:
  version: 2
  run_all:
    jobs:
      - build
      - debian_latest
