# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  bash_rc:
    description: "You know what I mean"
    steps:
      - run:
          name: "execute .bashrc"
          command: bash ./.bashrc
jobs:
  build:
    docker:
      - image: "debian:bullseye-20200327-slim"
    steps:
      - run:
          name: "install vim"
          command: |
            apt-get update && apt-get upgrade --yes
            apt-get install --yes vim git
      - checkout # Check out repo
      - bash_rc
          #debianLatest:
          #  docker:
          #    - image: "debian:latest"
          #  steps:
          #    - checkout # Check out repo
          #    - run:
          #        name: install
          #        command: bash ./.bashrc
        #      mac:
        #        macos:
        #
