#!/bin/bash
platform=$(uname)

if [ "$platform" == "Darwin" ]; then
  ip="ifconfig"
elif [ "$platform" == "Linux" ]; then
  ip="ip -4 addr"
else
  echo "Huh?! your platform is $platform. Not known."
  exit 1
fi

$ip | grep -o -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127\.0\.0\.1 | grep -E -v "([0-9]{1,3}\.){3}255"
#vim: set ft=sh
