#!/bin/bash
pgrep ^mpd$ >/dev/null
if [[ $? == 0 ]]; then
  echo "mpd is already running"
else
  echo "mpd not running, executing now..."
  mpd
fi

pgrep ^mpdas$ >/dev/null
if [[ $? == 0 ]]; then
  echo "mpdas is already running"
else
  echo "mpdas is not running, executing now..."
  mpdas -c ~/.mpdasrc -d
fi

pgrep ^vimpc$ >/dev/null
if [[ $? == 0 ]]; then
  echo "vimpc is already running"
else
  echo "vimpc is not running. Hit any key to execute it..."
  read -n 1 -s
  vimpc
fi
