#!/bin/bash
pidof "mpd" >/dev/null
if [[ $? == 0 ]]; then
  echo "mpd is already running"
else
  echo "mpd not running, executing now..."
  mpd
fi

pidof "mpdas" >/dev/null
if [[ $? == 0 ]]; then
  echo "mpdas is already running"
else
  echo "mpdas is not running, executing now..."
  mpdas -c ~/.mpdasrc -d
fi

pidof "ncmpcpp" >/dev/null
if [[ $? == 0 ]]; then
  echo "ncmpcpp is already running"
else
  echo "ncmpcpp is not running, executing now..."
  sleep 2
  ncmpcpp
fi
